### PR TITLE
This adds .NET 3 tests in CI.

### PR DESCRIPTION
**Pull request by lemire**
Should be self-explanatory.

### CODE REVIEW

**Comment by lemire** [comment]
@CarlVerret Can you have a look? I think we should find a way to test systematically with 3.1 if the README claims to support 3.1.

**Comment by CarlVerret** [comment]
Even on local plateform, I had some issues with benchmark.net when I tried to measure perf under .net 3.1. 
Couldn't find a way to run both jobs (3.1 /5.0) with my installed version of Benchmark.net

**Comment by lemire** [comment]
@CarlVerret Well, the benchmark is not a primary concern. It would be fine to only benchmark 5.0. What I'd like to run on both platforms are the tests. 

I'm sure we can find help.

**Comment by CarlVerret** [comment]
Done !

**Pull request closed without merging**
