### PR TITLE
Utf8Parser benchmark

### LINKED ISSUE #40: Compare to Utf8Parser
Utf8Parser and Utf8Formatter are out-of-the-box high-performance number parsers, it would be great to see how this lib performs against them.

### PR DESCRIPTION
**Pull request by LordJZ**
Fixes #40

### CODE REVIEW

**Comment by LordJZ** [comment]
csFastFloat seems to be about 50% faster than Utf8Parser. Pretty good!

**Comment by lemire** [comment]
@LordJZ This is a great contribution. I would argue that it is not entirely fair since, as observed elsewhere, there are optimization that csFastFloat is unable to do given that it assumes UTF16 input. To put it another way, there is much room for optimization if we want to focus on UTF8 inputs.

**Comment by lemire** [comment]
@LordJZ Please see this issue: https://github.com/CarlVerret/csFastFloat/issues/43

I think that if we are serious about UTF-8, we have to provide a csFastFloat parser that runs over UTF-8 inputs.

**Comment by LordJZ** [comment]
csFastFloat does not really do anything specific for unicode, it just reads twice more bytes.

**Comment by buybackoff** [comment]
> I think that if we are serious about UTF-8, we have to provide a csFastFloat parser that runs over UTF-8 inputs.

Yes, please! 😄 

Utf8 double parsing is the bottleneck whenever doubles are present in JSON e.g. in this very fast JSON serialier: https://github.com/neuecc/Utf8Json/tree/master/src/Utf8Json/Internal/DoubleConversion

Quoting Utf8Json readme:
> Number conversion is often high cost. If target encoding is UTF8 only, we can use itoa algorithm so avoid int.ToString and UTF8 encode cost. Especialy double-conversion, Utf8Json ported [google/double-conversion](https://github.com/google/double-conversion) algorithm, it is fast dtoa and atod works.

It's essential for zero-copy parsing: when input bytes are UTF8 it's probably more expensive to convert to UTF16 than to just do parsing of raw bytes. Most JSON/CSV payloads are UTF8/ASCII.

**Comment by lemire** [comment]
> csFastFloat does not really do anything specific for unicode, it just reads twice more bytes.

That's correct but UTF-8 inputs allow optimizations that are otherwise not possible.

**Comment by lemire** [comment]
Merging to dlemire/fast_utf8.

**Pull request merged**
