### PR TITLE
This updates the unit tests so that we can run all of them in CI. All of the time.

### PR DESCRIPTION
**Pull request by lemire**
We have very efficient tests, so there is no reason not to run them.

### CODE REVIEW

**Comment by CarlVerret** [comment]
ok, i'll just make sure there's not "local culture" interference in my
tests.  Had some issues with my approval tests regarding decimal
separator...

**Comment by lemire** [comment]
@CarlVerret Note that this PR disables these tests when the additional tooling not provided by `dotnet` is not found (e.g., a desktop app like TortoiseDiff).

**Comment by lemire** [comment]
@CarlVerret 

Please note that ApprovalTests has an external dependency on a diff tool and if such a diff tool is not found, it does not handle it gracefully. Instead, it just fails the tests. For obvious reasons, it is undesirable.

```
❯ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  csFastFloat -> /home/lemire/CVS/github/csFastFloat/csFastFloat/bin/Debug/net5.0/csFastFloat.dll
  csFastFloat -> /home/lemire/CVS/github/csFastFloat/csFastFloat/bin/Debug/netcoreapp3.1/csFastFloat.dll
  Successfully created package '/home/lemire/CVS/github/csFastFloat/csFastFloat/bin/Debug/csFastFloat.1.0.0.nupkg'.
  TestcsFastFloat -> /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/bin/Debug/netcoreapp3.1/TestcsFastFloat.dll
  TestcsFastFloat -> /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/bin/Debug/net5.0/TestcsFastFloat.dll
Test run for /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/bin/Debug/net5.0/TestcsFastFloat.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.8.3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.90]     TestcsFastFloat.Tests.Exaustive.FastParserTest.All32BitsValues [SKIP]
  Skipped TestcsFastFloat.Tests.Exaustive.FastParserTest.All32BitsValues [1 ms]
[xUnit.net 00:00:01.27]     TestcsFastFloat.Tests.Basic.BasicTests.Issue19 [SKIP]
[xUnit.net 00:00:01.28]     TestcsFastFloat.Tests.ff_suppl_tests.SupplFilesTest.AllFiles [FAIL]
[xUnit.net 00:00:01.29]     TestcsFastFloat.Tests.Basic.BasicTests.issue40 [FAIL]
  Skipped TestcsFastFloat.Tests.Basic.BasicTests.Issue19 [1 ms]
  Failed TestcsFastFloat.Tests.ff_suppl_tests.SupplFilesTest.AllFiles [15 ms]
  Error Message:
   System.ArgumentException : Invalid search path
  Stack Trace:
     at TestcsFastFloat.Tests.ff_suppl_tests.SupplFilesTest.AllFiles() in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/suppl_tests/SupplFilesTest.cs:line 24
  Failed TestcsFastFloat.Tests.Basic.BasicTests.issue40 [12 ms]
  Error Message:
   Assert.Throws() Failure
Expected: typeof(System.FormatException)
Actual:   (No exception was thrown)
  Stack Trace:
     at TestcsFastFloat.Tests.Basic.BasicTests.issue40() in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/Basic/BasicTests.cs:line 43
[xUnit.net 00:00:01.30]     TestcsFastFloat.Tests.Basic.TestDoubleParser.ParseNumber_Works_Scnenarios [FAIL]
[xUnit.net 00:00:01.30]     TestcsFastFloat.Tests.Basic.TestFloatParser.ParseNumber_Works_Scenarios [FAIL]
  Failed TestcsFastFloat.Tests.Basic.TestDoubleParser.ParseNumber_Works_Scnenarios [23 ms]
  Error Message:
   System.Exception : Could not find a diff tool for extension: .txt
  Stack Trace:
     at ApprovalTests.Reporters.DiffReporter.Report(String approved, String received) in C:\projects\approvaltests-net\src\ApprovalTests\Reporters\DiffReporter.cs:line 17
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvers\FileApprover.cs:line 65
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Core\Approver.cs:line 13
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 71
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 52
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 124
   at ApprovalTests.Approvals.Verify(Object text) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 171
   at TestcsFastFloat.Tests.BaseTestClass.VerifyData[T](T data, String nomScenario) in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/BaseTestClass.cs:line 24
   at TestcsFastFloat.Tests.Basic.TestDoubleParser.ParseNumber_Works_Scnenarios() in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/Basic/TestDoubleParser.cs:line 145
  Failed TestcsFastFloat.Tests.Basic.TestFloatParser.ParseNumber_Works_Scenarios [200 ms]
  Error Message:
   System.Exception : Could not find a diff tool for extension: .txt
  Stack Trace:
     at ApprovalTests.Reporters.DiffReporter.Report(String approved, String received) in C:\projects\approvaltests-net\src\ApprovalTests\Reporters\DiffReporter.cs:line 17
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvers\FileApprover.cs:line 65
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Core\Approver.cs:line 13
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 71
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 52
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 124
   at ApprovalTests.Approvals.Verify(Object text) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 171
   at TestcsFastFloat.Tests.BaseTestClass.VerifyData[T](T data, String nomScenario) in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/BaseTestClass.cs:line 24
   at TestcsFastFloat.Tests.Basic.TestFloatParser.ParseNumber_Works_Scenarios() in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/Basic/TestFloatParser.cs:line 200

Failed!  - Failed:     4, Passed:   196, Skipped:     2, Total:   202, Duration: 679 ms - /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/bin/Debug/net5.0/TestcsFastFloat.dll (net5.0)
Test run for /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/bin/Debug/netcoreapp3.1/TestcsFastFloat.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.97]     TestcsFastFloat.Tests.Exaustive.FastParserTest.All32BitsValues [SKIP]
  Skipped TestcsFastFloat.Tests.Exaustive.FastParserTest.All32BitsValues [1 ms]
[xUnit.net 00:00:01.37]     TestcsFastFloat.Tests.Basic.BasicTests.Issue19 [SKIP]
  Skipped TestcsFastFloat.Tests.Basic.BasicTests.Issue19 [1 ms]
[xUnit.net 00:00:01.38]     TestcsFastFloat.Tests.Basic.BasicTests.issue40 [FAIL]
[xUnit.net 00:00:01.39]     TestcsFastFloat.Tests.ff_suppl_tests.SupplFilesTest.AllFiles [FAIL]
  Failed TestcsFastFloat.Tests.Basic.BasicTests.issue40 [13 ms]
  Error Message:
   Assert.Throws() Failure
Expected: typeof(System.FormatException)
Actual:   (No exception was thrown)
  Stack Trace:
     at TestcsFastFloat.Tests.Basic.BasicTests.issue40() in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/Basic/BasicTests.cs:line 43
  Failed TestcsFastFloat.Tests.ff_suppl_tests.SupplFilesTest.AllFiles [18 ms]
  Error Message:
   System.ArgumentException : Invalid search path
  Stack Trace:
     at TestcsFastFloat.Tests.ff_suppl_tests.SupplFilesTest.AllFiles() in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/suppl_tests/SupplFilesTest.cs:line 26
[xUnit.net 00:00:01.39]     TestcsFastFloat.Tests.Basic.TestFloatParser.ParseNumber_Works_Scenarios [FAIL]
[xUnit.net 00:00:01.40]     TestcsFastFloat.Tests.Basic.TestDoubleParser.ParseNumber_Works_Scnenarios [FAIL]
  Failed TestcsFastFloat.Tests.Basic.TestFloatParser.ParseNumber_Works_Scenarios [200 ms]
  Error Message:
   System.Exception : Could not find a diff tool for extension: .txt
  Stack Trace:
     at ApprovalTests.Reporters.DiffReporter.Report(String approved, String received) in C:\projects\approvaltests-net\src\ApprovalTests\Reporters\DiffReporter.cs:line 19
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvers\FileApprover.cs:line 65
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Core\Approver.cs:line 13
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 71
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 52
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 124
   at ApprovalTests.Approvals.Verify(Object text) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 171
   at TestcsFastFloat.Tests.BaseTestClass.VerifyData[T](T data, String nomScenario) in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/BaseTestClass.cs:line 24
   at TestcsFastFloat.Tests.Basic.TestFloatParser.ParseNumber_Works_Scenarios() in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/Basic/TestFloatParser.cs:line 200
  Failed TestcsFastFloat.Tests.Basic.TestDoubleParser.ParseNumber_Works_Scnenarios [28 ms]
  Error Message:
   System.Exception : Could not find a diff tool for extension: .txt
  Stack Trace:
     at ApprovalTests.Reporters.DiffReporter.Report(String approved, String received) in C:\projects\approvaltests-net\src\ApprovalTests\Reporters\DiffReporter.cs:line 19
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvers\FileApprover.cs:line 65
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Core\Approver.cs:line 13
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 71
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 52
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 124
   at ApprovalTests.Approvals.Verify(Object text) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 171
   at TestcsFastFloat.Tests.BaseTestClass.VerifyData[T](T data, String nomScenario) in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/BaseTestClass.cs:line 24
   at TestcsFastFloat.Tests.Basic.TestDoubleParser.ParseNumber_Works_Scnenarios() in /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/Basic/TestDoubleParser.cs:line 145

Failed!  - Failed:     4, Passed:   196, Skipped:     2, Total:   202, Duration: 734 ms - /home/lemire/CVS/github/csFastFloat/TestcsFastFloat/bin/Debug/netcoreapp3.1/TestcsFastFloat.dll (netcoreapp3.1)```

**Comment by lemire** [comment]
@CarlVerret Note that this is apparently deliberate:

https://github.com/approvals/ApprovalTests.Net/blob/d3d4a978aa297444f284eb1a7d5b58f442e0869a/src/ApprovalTests/Reporters/DiffReporter.cs#L6-L26

As far as I can tell, you must have one of these tools installed...

https://github.com/VerifyTests/DiffEngine#supported-tools

*and* the tool must be detected.

If the tool is not present or not detected, then the default is to throw an exception which `dotnet` views as an error. My proposal is to catch exceptions.

A smarter approach upstream would be to disable the tests where a supported diff tool is not found, maybe with a warning.

**Comment by lemire** [comment]
@CarlVerret I like what you are doing.

**Comment by lemire** [comment]
Let us merge!!!

**Comment by lemire** [comment]
Merged.

**Pull request merged**
